name: Sentinel

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:

jobs:
  run-test:
    name: run-test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        container: ["fusroman/fink_fat_docker:dev"]

    container:
      image: ${{ matrix.container }}

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up env [1/2]
      run: |
        echo "FINK_GRB=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV
        echo "${BINPATH}" >> $GITHUB_PATH

    - name: Set up env [2/2]
      run: |
        echo "PYTHONPATH="${PYTHONPATH}:${SPARKLIB}:${FINK_GRB}"" >> $GITHUB_ENV

    - name: Install fink-broker
      run: |
        git clone https://github.com/astrolabsoftware/fink-broker.git
        cd fink-broker
        pip install .
        cd ../
        export FINK_HOME=$HOME/fink-broker
        export PATH=$PATH:$FINK_HOME/bin
        export PYTHONPATH=$PYTHONPATH:$FINK_HOME
    
    - name: Install requirements
      run: |
        cat requirements.txt
        pip install -r requirements.txt

    - name: Check env
      run: |
        echo "FINK_GRB: $FINK_GRB"
        echo "SPARK_HOME: $SPARK_HOME"
        echo "SPARKLIB: $SPARKLIB"
        echo "PYTHONPATH: $PYTHONPATH"
        echo "JAVA_HOME: $JAVA_HOME"
        echo "FINK_HOME: $FINK_HOME"
        echo `python -V`

    - name: Run test suites
      run: |
        ./run_test.sh
        curl -s https://codecov.io/bash | bash
